title: TESA FC
description: Website TESA FC
permalink: pretty
timezone: Asia/Jakarta
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
author:
  name: TESA FC
  email: terassaungfc@gmail.com
collections:
  players:
    output: true
  matches:
    output: true
defaults:
  - scope:
      path: ""
      type: "players"
    values:
      layout: "player"
      header: "header-player"
version: 1.0.0
