title: tesa fc
description: official website tesa fc
permalink: pretty
timezone: Asia/Jakarta
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
author:
  name: tesa fc
  email: terassaungfc@gmail.com
collections:
  players:
    output: true
  matches:
    output: true
defaults:
  - scope:
      path: ""
      type: "players"
    values:
      layout: "player"
      header: "header-player"
  - scope:
      path: ""
      type: "matches"
    values:
      layout: "match"
      header: "header-match"
version: 1.0.0
